export default {
  colors: {
    primary: '#5F6AC4',
    secondary: '#FFFFFF',
    white: '#FFFFFF',
    black: '#000000',
    grey: '#AFAFAF',
    header: '#1B1B1F',
    text: '#7A7A80',
    text_detail: '#AEAEB3',
    title: '#47474D',
    line: '#EBEBF0',
    main: '#DC1637',
    main_light: '#FDEDEF',
    success: '#03B252',
    shape: '#E1E1E8',
    shape_dark: '#29292E',
  },
  fonts: {
    GilroyEB: 'Gilroy-ExtraBold',
    GilroyL: 'Gilroy-Light',
    InterB: 'Inter-Bold',
    InterM: 'Inter-Medium',
    InterR: 'Inter-Regular',
    InterSB: 'Inter-SemiBold',
    MontEB: 'Montserrat-ExtraBold',
    MontM: 'Montserrat-Medium',
    MontR: 'Montserrat-Regular',
    MontSB: 'Montserrat-SemiBold',
    PoppinsB: 'Poppins-Bold',
    PoppinsM: 'Poppins-Medium',
    PoppinsR: 'Poppins-Regular',
    PoppinsSB: 'Poppins-SemiBold',
    RobotoB: 'Roboto-Bold',
    RobotoM: 'Roboto-Medium',
    RobotoR: 'Roboto-Regular',
    SkB: 'Sk-Modernist-Bold',
    SkM: 'Sk-Modernist-Mono',
    SkR: 'Sk-Modernist-Regular',
  },
};
